export const SUPPORTED_FIAT_CURRENCIES = {
  USD: 'USD',
  EUR: 'EUR'
};
export const FEATURED_FIAT_CURRENCY = SUPPORTED_FIAT_CURRENCIES.USD;

export const FEATURED_FIAT_CURRENCY_SYMBOL = '$';

export const CURRENCY_PRECISION = 2;