export const SUPPORTED_FIAT_CURRENCIES = {
  USD: 'USD',
  EUR: 'EUR',
  GBP: 'GBP'
};
export const MAIN_CURRENCY = SUPPORTED_FIAT_CURRENCIES.USD;

export const FEATURED_FIAT_CURRENCY_SYMBOL = '$';

export const CURRENCY_PRECISION = 2;